[tasks.run]
description = "Bring containers up"
run = "op run -- podman compose up -d"

[env]
ATUIN_DB_NAME = "op://k/atuin/database"
ATUIN_DB_USERNAME = "op://k/atuin/username"
ATUIN_DB_PASSWORD = "op://k/atuin/password"
TS_AUTHKEY = "op://k/atuin/tailscale oauth client secret"
